CREATE TABLE IF NOT EXISTS budgets (
  id SERIAL PRIMARY KEY,
  name VARCHAR NOT NULL,
  amount VARCHAR NOT NULL,
  icon VARCHAR,
  "createdBy" VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS incomes (
  id SERIAL PRIMARY KEY,
  name VARCHAR NOT NULL,
  amount VARCHAR NOT NULL,
  icon VARCHAR,
  "createdBy" VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS expenses (
  id SERIAL PRIMARY KEY,
  name VARCHAR NOT NULL,
  amount NUMERIC NOT NULL DEFAULT 0,
  "budgetId" INTEGER REFERENCES budgets(id),
  "createdAt" VARCHAR NOT NULL
); 